version: "3"

volumes:
  productdata:

networks:
  backend:
  frontend:

services:
  ntytl:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
     - backend
     - frontend
    environment:
     - DBHOST=mysql
    ports:
     - 3000:80
    depends_on:
     - mysql
  mysql:
    image: "mysql:8.0.0"
    volumes:
     - productdata:/var/lib/mysql
    networks:
     - backend
    environment:
     - MYSQL_ROOT_PASSWORD=mysecret
     - bind-address=0.0.0.0
